---
title: ""
output: html_document
---


```{r setup, include=FALSE, echo=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(plotly)
library(ggplot2)
library(shinydashboard)
library(leaflet)
library(DT)
source("loadGlobals.R")
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
source("loadGlobals.R")
flat_file %>%
  group_by(month) %>% 
  summarize(Filings = n()) %>% 
  plot_ly(type = "bar", 
          x=~month, 
          y=~Filings,
          hovertemplate=paste("%{yaxis.title.text}: %{y}<br>",
                              "%{x}")) %>% 
  layout(title = "Oregon Evictions - Filings per Month since Jan 20'",
         showlegend = FALSE,
         xaxis = list(title = ""),
         yaxis = list(title = "Number of Cases")) %>% 
  add_markers(x = "2020-03-01",
              y = 1000,
              showlegend = FALSE) %>% 
  add_annotations(x = "2020-03-01",
                  y = 1000,
                  xref = "x",
                  yref = "y",
                  text = "EO 20-13 Goes into effect <br> HB 4213 Goes into effect <br> (retroactive)",
                  xanchor = 'left',
                  bgcolor="white",
                  bordercolor="black") %>% 
  add_segments(x = "2020-03-01", xend = "2020-03-01", y = 0, yend = 1600, line = list(dash = "dash")) %>% 
  add_markers(x = "2020-09-01",
              y = 500,
              showlegend = FALSE) %>% 
  add_annotations(x = "2020-09-01",
                  y = 500,
                  xref = "x",
                  yref = "y",
                  text = "HB 4213 Emergency Period Ends <br> EO 20-56 Goes into effect",
                  xanchor = 'center',
                  bgcolor="white",
                  bordercolor="black") %>% 
  add_segments(x = "2020-09-01", xend = "2020-09-01", y = 0, yend = 1600, line = list(dash = "dash")) %>%
  add_markers(x = "2020-12-01",
              y = 750,
              showlegend = FALSE) %>% 
  add_annotations(x = "2020-12-01",
                  y = 750,
                  xref = "x",
                  yref = "y",
                  text = "EO 20-56 Emergency Period Ends <br> HB 4401 Goes into effect",
                  xanchor = 'center',
                  bgcolor="white",
                  bordercolor="black") %>% 
  add_segments(x = "2020-12-01", xend = "2020-12-01", y = 0, yend = 1600, line = list(dash = "dash")) %>%
  add_markers(x = "2021-06-01",
              y = 950,
              showlegend = FALSE) %>% 
  add_annotations(x = "2021-06-01",
                  y = 950,
                  xref = "x",
                  yref = "y",
                  text = "HB 4401 Emergency Period Ends <br> SB 278 Goes into effect",
                  xanchor = 'center',
                  bgcolor="white",
                  bordercolor="black") %>% 
  add_segments(x = "2021-06-01", xend = "2021-06-01", y = 0, yend = 1600, line = list(dash = "dash")) %>%
  config(displayModeBar = F)
```